#!/usr/bin/ruby

require 'rest_client'
require 'ccsv'
require 'zip/zip'
require 'zip/zipfilesystem'


def unzip_file(file)
  Zip::ZipFile.open(file) { |zip_file|
    zip_file.each{|f|
      zip_file.extract(f, "db/simulation/" + f.to_s)
    }
  }
end

def run(filename)
  imei_number = File.basename(filename, ".csv")
  begin
    is_header = true
    Ccsv.foreach(filename) do |row|
      if is_header
        is_header = false
        next
      end
      next if row[1] == /Date:/
      next if row[0] =~ /Alarme:/
      next if row[0] =~ /Total:/
      event = {
        date: row[1].gsub('"', ''),
        imei_number: imei_number,
        latitude: row[2].gsub('"', ''),
        longitude: row[3].gsub('"', ''),
        speed: row[4].gsub('"', ''),
        gps_signal: row[5].gsub('"', ''),
        heading: row[6].gsub('"', '')
      }
RestClient.post "http://#{ARGV[0]}/events", {data: event}
      print "."
      sleep(5)
    end
  rescue Exception => e
    puts "ERROR: #{filename}"
    puts e
  end

end

threads = []

Dir[File.expand_path(File.dirname(__FILE__) + '/../db/simulation/*.zip')].each do |archive|
  filename = archive.split('.')
  csv_file = archive[0..archive.length()-5]
  unzip_file(archive)
  threads << Thread.start do
    puts "Reading data from #{csv_file}"
    run(csv_file)
    File.delete(csv_file)
  end
end

threads.each {|t| t.join}
