#!/usr/bin/ruby

require 'rest_client'
require 'ccsv'

def run(filename)
  imei_number = File.basename(filename, ".csv")
  begin
    is_header = true
    Ccsv.foreach(filename) do |row|
      if is_header
        is_header = false
        next
      end
      next if row[1] == /Date:/
      next if row[0] =~ /Alarme:/
      next if row[0] =~ /Total:/
      event = {
        date: row[1].gsub('"', ''),
        imei_number: imei_number,
        latitude: row[2].gsub('"', ''),
        longitude: row[3].gsub('"', ''),
        speed: row[4].gsub('"', ''),
        gps_signal: row[5].gsub('"', ''),
        heading: row[6].gsub('"', '')
      }
		 	RestClient.post "http://#{ARGV[0]}/events", {data: event}
      print "."
      sleep(5)
    end
  rescue Exception => e
    puts "ERROR: #{filename}"
    puts e
  end

end

threads = []

Dir[File.expand_path(File.dirname(__FILE__) + '/../db/simulation/*.csv')].each do |filename|
	threads << Thread.start do
		puts "Reading data from #{filename}"
		run(filename)
	end
end

threads.each {|t| t.join}
